### PR TITLE
Add Jurassic Ninja support for Jetpack CRM plugin

### PR DESCRIPTION
**Pull request by cleacos**
Add Jurassic Ninja support for Jetpack CRM plugin

This PR adds two ways to install the plugin, the normal method through the WP plugin repository, and another method to install it from the master branch.

### CODE REVIEW

**Comment by oskosk** [comment]
It seems likek the repo is private and thus Jurassic Ninja is not currently able to fetch the zip file

**Comment by cleacos** [comment]
@oskosk can we merge it and don't add the checkbox option for it? What happens with Travis-CI checks? I see that it's failing by some code styling in other files (not in this PR). Thanks

**Comment by cleacos** [comment]
Our team plan to make the repository public soon

**Review by oskosk — APPROVED** [review]
LGTM! merging

**Pull request merged**
