### PR TITLE
Licensing: Add support for Jetpack Licenses in SpecialOps

### PR DESCRIPTION
**Pull request by atanas-dev**
Add support for Jetpack Licenses in SpecialOps:
Screenshot 2020-10-02 at 19 18 52

Requires an OAuth2 Token to be stored in a new "Jetpack Licensing API OAuth2 Token" settings field:
Screenshot 2020-10-02 at 18 12 16

To add the new license options the content of the `/specialops` page has to be edited like so:
```diff
<li>
<div class="checkbox"><label><input checked="checked" type="checkbox" data-feature="jetpack">&nbsp;Include Jetpack</label>
+[jn_jetpack_products_list]
</li>
```

This PR also adds suggested content for the `/create` and `/specialops` pages under /docs/.

**Important Note:** Since Jetpack 9.0 is not out yet you need to enable the Jetpack Beta plugin and enter `rc` for the branch in order to have Jetpack recognize and attach licenses to your JN site.

### CODE REVIEW

**Comment by poisa** [comment]
Finally got around to testing this. I only did a functional test and it all works as expected. I will take a deeper look at the code on monday. 

At first sight I'm not seeing anything that will revoke the issued licenses when the sites are purged. But again, I'll take a deeper dive on monday.

**Comment by atanas-dev** [comment]
@poisa this is why I suggested having specs in Asana 😆 
I've added the functionality so licenses now get revoked when a site is purged.

**Comment by poisa** [comment]
> this is why I suggested having specs in Asana otherwise I miss stuff like this

I only ignore your requests because I care. Don't worry, next time we'll add more thorough specs.

So, this looks good to me and is ready to go. oskosk asked me to add the smaller things that I found (documentation-wise) to this PR but I'm not seeing how I can do that. If I pull your branch and add a commit to it, will it show up here? 🤔 

Also, I chatted with Oli today and he's going to need the endpoint to expose all the provisionable items on the licensing API. Should we work on that, implement it here, and then merge this? Or would you like to just merge this and then make another PR? Whatever you decide is fine by me.

**Comment by atanas-dev** [comment]
> If I pull your branch and add a commit to it, will it show up here? 🤔

Yes, this PR is based on a branch so any commits to that branch will be reflected here so feel free to commit and push.

> Should we work on that, implement it here, and then merge this?

I think we should merged this and add the provisionable items endpoint integration in a separate PR.

**Comment by poisa** [comment]
I'm updating the `README.md` file and see that the new file `create.md` should actually be called `home.md` because that's what the home page should contain. The contents of the `/create` page are described in the README itself. Are you OK with me renaming this file?

**Comment by atanas-dev** [comment]
You are correct - go ahead!

**Comment by poisa** [comment]
@oskosk do you need anything else from us on this?

**Review by oskosk — APPROVED** [review]

**Pull request merged**
