### PR TITLE
Update woocommerce-beta-tester plugin url

### PR DESCRIPTION
**Pull request by designsimply**
https://github.com/woocommerce/woocommerce-beta-tester/archive/master.zip is returning a 404 for me but https://github.com/woocommerce/woocommerce-beta-tester/archive/refs/heads/trunk.zip works—which I copied from the "Download ZIP" option on the GitHub repo main page.

### CODE REVIEW

**Comment by designsimply** [comment]
Fixes #230.

**Comment by oskosk** [comment]
thanks ❤️  will deploy later!

**Comment by oskosk** [comment]
Sorry for the delay. @designsimply. It's depoyed now

**Comment by designsimply** [comment]
Noooooo, thank **you** for working on this! It's wonderful.

Just tested out the `woocommerce-beta-tester` option and it worked like a charm. 🎉

**Pull request merged**
