### PR TITLE
Add username/password/autologin create options

### PR DESCRIPTION
**Pull request by brbrr**

### CODE REVIEW

**Comment by oskosk** [comment]
I really don’t think we should go this way

**Comment by oskosk** [comment]
It adds complexity to the create page and introduces the ability to make site credentials be difficult to remember which is the basic and whole point of this software. Also not a good idea IMO to make the autologin plugin be optional from this page

**Comment by oskosk** [comment]
If we add this functionality there’s absolutely no benefit in running e2e tests against JN as opposed to using the SP API directly and sshing into the box to run `wp` commands

**Comment by oskosk** [comment]
I've just rebased this one to deal with latest changes, just in case.

**Comment by brbrr** [comment]
I'm going to close this as not needed.

**Pull request closed without merging**
