### PR TITLE
Include trunk branch in the WooCommerce Beta Tester dropdown

### PR DESCRIPTION
**Pull request by chihsuan**
p1685350748192869/1684816055.228779-slack-C03CPM3UXDJ

This PR updates `getAvailableWooCommerceBetaBranches` function to include `master` (trunk) prop so that we can see the trunk branch in the WooCommerce Beta Tester Live Branches dropdown.

I've tested this in dev console on JN.

1. Go to JN
2. Open the dev console
3. Copy and paste the `getAvailableWooCommerceBetaBranches` function
4. Run `getAvailableWooCommerceBetaBranches().then(console.log)`
5. Should see the `trunk` item in the array.

### CODE REVIEW

**Comment by chihsuan** [comment]
Hey @samueljseay 👋  I noticed that https://github.com/woocommerce/woocommerce/pull/38536 has been merged. 🙌  This PR is ready for review. Could you please take a look when you get a chance? Thank you!

**Comment by samueljseay** [comment]
Hey @chihsuan yes I'm still aware of this one but I'll need to test it manually on JN, I'll try get to that this week. Sorry its taking a while.

**Comment by samueljseay** [comment]
@chihsuan tested this and it doesn't work quite yet, there are some additional changes we still need to make to the plugin itself. I'll add this to my task list for this week

**Comment by chihsuan** [comment]
> @chihsuan tested this and it doesn't work quite yet, there are some additional changes we still need to make to the plugin itself. I'll add this to my task list for this week

Thank you! 😃

**Comment by samueljseay** [comment]
@chihsuan turns out it was just an issue with which release of beta tester was picked up. this works perfectly. 🎉

**Pull request merged**
